version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data


  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
